export const photosConstant = {
    GET_PHOTOS_BY_TOPIC_REQUEST: 'GET_PHOTOS_BY_TOPIC_REQUEST',
    GET_PHOTOS_BY_TOPIC_SUCCESS: 'GET_PHOTOS_BY_TOPIC_SUCCESS',
    GET_PHOTOS_BY_TOPIC_FAIL: 'GET_PHOTOS_BY_TOPIC_FAIL',
}
export const authConstants = {
    AUTH_REQUEST: 'AUTH_REQUEST',
    AUTH_SUCEESS: 'AUTH_SUCEESS',
    AUTH_FAIL: 'AUTH_FAIL',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCEESS: 'LOGOUT_SUCEESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL'
}

